[package]
name = "rustic-library-sync-extension"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
rustic-extension-api = { git = "https://github.com/rustic-music-player/rustic.git" }
